### ISSUE TITLE
Can´t get project to run

### ISSUE THREAD

**Issue by SB97** [theShmoo/DSA5RegelWikiParser#1]
Python: 3.8.5
python3-scrapy: 1.7.3

```bash
steffen@pop-os:~/Dokumente/DSA5RegelWikiParser$ scrapy crawl skills
Traceback (most recent call last):
  File "/usr/bin/scrapy", line 11, in <module>
    load_entry_point('Scrapy==1.7.3', 'console_scripts', 'scrapy')()
  File "/usr/lib/python3/dist-packages/scrapy/cmdline.py", line 145, in execute
    cmd.crawler_process = CrawlerProcess(settings)
  File "/usr/lib/python3/dist-packages/scrapy/crawler.py", line 267, in __init__
    super(CrawlerProcess, self).__init__(settings)
  File "/usr/lib/python3/dist-packages/scrapy/crawler.py", line 145, in __init__
    self.spider_loader = _get_spider_loader(settings)
  File "/usr/lib/python3/dist-packages/scrapy/crawler.py", line 347, in _get_spider_loader
    return loader_cls.from_settings(settings.frozencopy())
  File "/usr/lib/python3/dist-packages/scrapy/spiderloader.py", line 61, in from_settings
    return cls(settings)
  File "/usr/lib/python3/dist-packages/scrapy/spiderloader.py", line 25, in __init__
    self._load_all_spiders()
  File "/usr/lib/python3/dist-packages/scrapy/spiderloader.py", line 47, in _load_all_spiders
    for module in walk_modules(name):
  File "/usr/lib/python3/dist-packages/scrapy/utils/misc.py", line 73, in walk_modules
    submod = import_module(fullpath)
  File "/usr/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 783, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/steffen/Dokumente/DSA5RegelWikiParser/regelwikiparser/spiders/karma_spider.py", line 7, in <module>
    from properties_parser import PropertiesParser
ModuleNotFoundError: No module named 'properties_parser'
```

**Comment by theShmoo** [comment]
The regel-wiki changed a lot in the last 4 years and I no longer work on this project. Sorry.
If you manage to run it please provide a pull request.
